# Cloudflare Workers 配置文件
# Qwen3-TTS API 代理服务

name = "audiofy-tts-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# 环境变量（需要在 Cloudflare Dashboard 中配置敏感信息）
# [vars]
# 这些变量应该通过 Cloudflare Dashboard 或 wrangler secret 命令设置，不要提交到代码库
# APP_SECRET = "your-app-secret"
# DASHSCOPE_API_KEY = "your-dashscope-api-key"

# Workers 配置
workers_dev = true

# 路由配置（生产环境）
# [[routes]]
# pattern = "audiofy-tts-proxy.luhuizhx.workers.dev/*"
# zone_name = "luhuizhx.workers.dev"
