build:
  maxIssues: 0
  excludeCorrectable: false
  weights:
  # complexity: 2
  # LongParameterList: 1
  # style: 1
  # comments: 1

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'FindingsReport'
    - 'FileBasedFindingsReport'
    - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
    # - 'TxtOutputReport'
    # - 'XmlOutputReport'
    - 'HtmlOutputReport'
    - 'MdOutputReport'
    - 'SarifOutputReport'

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  LongMethod:
    threshold: 80
  LargeClass:
    threshold: 600
  CyclomaticComplexMethod:
    threshold: 20

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'

performance:
  active: true

potential-bugs:
  active: true

style:
  active: true
  MaxLineLength:
    maxLineLength: 140
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
