name: KMP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Android Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Shared Module
        run: ./gradlew shared:compileDebugKotlinAndroid

      - name: Build Android Debug APK
        run: ./gradlew composeApp:assembleDebug

      - name: Run Shared Tests
        run: ./gradlew shared:testDebugUnitTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: shared/build/test-results/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk

  build-ios:
    name: iOS Build
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build iOS Framework (Simulator ARM64)
        run: ./gradlew linkDebugFrameworkIosSimulatorArm64

      - name: Upload Framework
        uses: actions/upload-artifact@v4
        with:
          name: ios-framework
          path: shared/build/bin/iosSimulatorArm64/debugFramework/

  compile-check:
    name: Compile Check (All Targets)
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Compile All Kotlin Metadata
        run: ./gradlew compileCommonMainKotlinMetadata

      - name: Compile Android Main
        run: ./gradlew compileDebugKotlinAndroid

      - name: Compile iOS Arm64
        run: ./gradlew compileKotlinIosArm64

      - name: Compile iOS Simulator Arm64
        run: ./gradlew compileKotlinIosSimulatorArm64
