name: KMP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run detekt
        run: ./gradlew detekt --no-daemon

      - name: Upload detekt report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: |
            **/build/reports/detekt/
            !**/build/reports/detekt/**/detekt.xml
          retention-days: 7

  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android Debug APK
        run: ./gradlew :composeApp:assembleDebug --no-daemon

      - name: Run Android Lint
        run: ./gradlew :composeApp:lintDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: composeApp/build/outputs/apk/debug/*.apk
          retention-days: 7

      - name: Upload Lint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-lint-report
          path: composeApp/build/reports/lint-results-debug.html
          retention-days: 7

  ios-build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build iOS Framework (Simulator)
        run: ./gradlew :composeApp:linkDebugFrameworkIosSimulatorArm64 --no-daemon

      - name: Upload iOS Framework
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-framework
          path: composeApp/build/bin/iosSimulatorArm64/debugFramework/
          retention-days: 7

  shared-module-tests:
    name: Shared Module Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run common tests
        run: ./gradlew :shared:testDebugUnitTest --no-daemon || echo "No tests found, skipping..."
        continue-on-error: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shared-test-results
          path: shared/build/test-results/
          retention-days: 7

  build-summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [code-quality, android-build, ios-build, shared-module-tests]
    if: always()
    steps:
      - name: Check build status
        run: |
          echo "Code Quality: ${{ needs.code-quality.result }}"
          echo "Android Build: ${{ needs.android-build.result }}"
          echo "iOS Build: ${{ needs.ios-build.result }}"
          echo "Shared Tests: ${{ needs.shared-module-tests.result }}"

          if [ "${{ needs.code-quality.result }}" != "success" ] || [ "${{ needs.android-build.result }}" != "success" ] || [ "${{ needs.ios-build.result }}" != "success" ]; then
            echo "❌ One or more critical jobs failed"
            exit 1
          fi

          echo "✅ All critical jobs passed"
